name: crear ejecutables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  create_release:
    permissions:
      contents: write
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.extract_version.outputs.version }}
      changes: ${{ steps.extract_changes.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
    
      - name: Install Toml
        run: pip install toml
      
      - name: Extract version
        id: extract_version
        run: |
          echo "::set-output name=version::$(python ./version.py)"

      - name: Extract Changes
        id: extract_changes
        run: |
          echo "::set-output name=changes::$(cat ./changes.txt)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: ${{ steps.extract_changes.outputs.changes }}
          draft: true
          prerelease: false

  build:
    needs: create_release
    permissions:
      contents: write

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install

      - name: Install pyInstaller
        run: pip install pyinstaller
      
      - name: Build
        run: pyinstaller --onefile --windowed --name "autoclicker-${{matrix.os}}" autoclicker/__init__.py
          
      - name: Get release file name for others
        if: matrix.os != 'windows-latest'
        run: echo "RELEASE_FILE_NAME=autoclicker-${{matrix.os}}" >>$GITHUB_ENV

      - name: Get release file name for windows
        if: matrix.os == 'windows-latest'
        run: echo "RELEASE_FILE_NAME=autoclicker-${{matrix.os}}.exe" >>$GITHUB_ENV

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./dist/${{ env.RELEASE_FILE_NAME }}
          asset_name: ${{ env.RELEASE_FILE_NAME }}
          asset_content_type: application/octet-stream
